#define SINGLE_COMMENT 257
#define MULTI_COMMENT 258
#define AUTO_KEYWORD 259
#define ENUM_KEYWORD 260
#define RESTRICT_KEYWORD 261
#define UNSIGNED_KEYWORD 262
#define BREAK_KEYWORD 263
#define EXTERN_KEYWORD 264
#define RETURN_KEYWORD 265
#define VOID_KEYWORD 266
#define CASE_KEYWORD 267
#define FLOAT_KEYWORD 268
#define SHORT_KEYWORD 269
#define VOLATILE_KEYWORD 270
#define CHAR_KEYWORD 271
#define FOR_KEYWORD 272
#define SIGNED_KEYWORD 273
#define WHILE_KEYWORD 274
#define CONST_KEYWORD 275
#define GOTO_KEYWORD 276
#define SIZEOF_KEYWORD 277
#define BOOL_KEYWORD 278
#define CONTINUE_KEYWORD 279
#define IF_KEYWORD 280
#define STATIC_KEYWORD 281
#define COMPLEX_KEYWORD 282
#define DEFAULT_KEYWORD 283
#define INLINE_KEYWORD 284
#define STRUCT_KEYWORD 285
#define IMAGINARY_KEYWORD 286
#define DO_KEYWORD 287
#define INT_KEYWORD 288
#define SWITCH_KEYWORD 289
#define DOUBLE_KEYWORD 290
#define LONG_KEYWORD 291
#define TYPEDEF_KEYWORD 292
#define ELSE_KEYWORD 293
#define REGISTER_KEYWORD 294
#define UNION_KEYWORD 295
#define IDENTIFIER 296
#define INTEGER_CONSTANT 297
#define FLOAT_CONSTANT 298
#define ENUMERATION 299
#define CHAR_CONSTANT 300
#define STRING_LITERAL 301
#define PUNCTUATOR 302
#ifdef YYSTYPE
#undef  YYSTYPE_IS_DECLARED
#define YYSTYPE_IS_DECLARED 1
#endif
#ifndef YYSTYPE_IS_DECLARED
#define YYSTYPE_IS_DECLARED 1
typedef union {
  int intval;
  float floatval;
  char *charval;
} YYSTYPE;
#endif /* !YYSTYPE_IS_DECLARED */
extern YYSTYPE yylval;
